// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MergeFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergeFiles'](arg1, arg2, arg3);
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}

export function SelectSaveLocation(arg1) {
  return window['go']['main']['App']['SelectSaveLocation'](arg1);
}

export function SelectZipFile() {
  return window['go']['main']['App']['SelectZipFile']();
}
