// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeTuzhong(arg1) {
  return window['go']['main']['App']['AnalyzeTuzhong'](arg1);
}

export function ExtractFromTuzhong(arg1, arg2) {
  return window['go']['main']['App']['ExtractFromTuzhong'](arg1, arg2);
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function MergeFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergeFiles'](arg1, arg2, arg3);
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function SelectExtractLocation(arg1) {
  return window['go']['main']['App']['SelectExtractLocation'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}

export function SelectSaveLocation(arg1) {
  return window['go']['main']['App']['SelectSaveLocation'](arg1);
}

export function SelectTuzhongFile() {
  return window['go']['main']['App']['SelectTuzhongFile']();
}
